version: '3.3'
services:
  database:
    build: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'yama_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'