package org.fhtech.yamaServer.controllers;


import org.fhtech.yama.movies.*;
import org.fhtech.yamaServer.services.MovieService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ws.server.endpoint.annotation.Endpoint;
import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.RequestPayload;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;

@Endpoint
public class MovieEndpoint {
    private static final String NAMESPACE_URI = "http://fhtech.org/yama/movies";

    private MovieService movieService;

    public MovieEndpoint(@Autowired MovieService movieService) {
        this.movieService = movieService;
    }

    @PayloadRoot(namespace = NAMESPACE_URI, localPart = "searchMovieRequest")
    @ResponsePayload
    public SearchMovieResponse getMovies(@RequestPayload SearchMovieRequest request) {

        //TODO: what is the cleanest way to do this (Movie class generated by jaxb2 plugin
        // isnt the same as our domain Movie so a huge amount of conversion is necessary)

        SearchMovieResponse response = new SearchMovieResponse();
        var domainMovies = movieService.findMoviesByTitleContains(request.getSearchString());
//        response.getMovies()
//                .addAll(MovieConverter.convertToXMLMovies(domainMovies));
        return response;
    }


//    //TODO: exercise says only import if studio and actors already exist (why are they listed in the xml then and not just ids?) should i search if they exist or import them myself beforehand
//    @PayloadRoot(namespace = NAMESPACE_URI, localPart = "importMovieRequest")
//    @ResponsePayload
//    public ImportMovieResponse importMovies(@RequestPayload ImportMovieRequest request) {
//        ImportMovieResponse response = new ImportMovieResponse();
//        movieService.saveAll(request.getMovies());
//    }


}